#Fichier permettant de créer notre service client
version: "3.7"

services:
  server:
    image: 192.168.1.69:5000/pluma-server:latest
    deploy:
      replicas: 6
    ports: 
      - 3001:3001
    env_file: ./server/.env
    networks:
      - pluma-network

  networks:
    pluma-network:
