# To start all app containers and have them talking to each other, in the
# root folder /, run 'docker-compose up'.
# Refer to /README.md for more information.

# Docker Compose File Format Version.
version: "3.7"

services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    env_file:
      - ../../bdd/mariadb.env
    ports:
      - 3307:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../../bdd/mymaria.cnf:/etc/mysql/conf.d/mymaria.cnf
    networks:
      - mariadb-network

  ## Interface graphique pour gérer les bases de données mariadb
  adminer:
    image: adminer:latest
    container_name: my-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mariadb-network

  ## Defining the Neo4j Database Service        
  neo:
    # The image to use
    image: neo4j:latest
    restart: always
    # map the ports so we can check the db server is up
    ports: 
      - 7474:7474
      - 7687:7687
    # mounting a named volume to the container to track db data
    volumes:
      - neo4j_data:/data/
    env_file:
      - ../../bdd/env.neo4j
    networks:
      - neo4j-network

  ## Conteneur du backend de Pluma
  server:
    container_name: pluma-server
    build:
      context: ./server
    restart: always
    env_file: ./server/.env
    networks:
      - neo4j-network
      - mariadb-network

  ## Conteneur proxy pour afficher pluma avec une url spécifique
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - neo4j-network
      - mariadb-network
      - pluma-network

  ## Conteneur du frontend de Pluma
  client:
    container_name: pluma-client
    build:
      context: ./client
    # This will force server service to build and start before client.
    depends_on:
      - server
    restart: always
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - neo4j-network
      - mariadb-network
      - pluma-network
    
volumes:
    neo4j_data:
    mariadb_data:
     
networks:
  neo4j-network:
    driver: bridge
  mariadb-network:
    driver: bridge
  pluma-network:
    driver: bridge
