#Fichier permettant de créer notre stack Pluma
version: "3.7"

services:
  server:
    image: 192.168.1.69:5000/pluma-server:latest
    deploy:
      replicas: 6
    ports: 
      - 3001:3001
    env_file: ./server/.env
    networks:
      - pluma-network
      
  client:
    image: 192.168.1.69:5000/pluma-client:latest
    deploy:
      replicas: 6
    depends_on:
      - server
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - pluma-network
      
  portainer:
    image: portainer/portainer-ce
    deploy:
      replicas: 6
    ports:
      - 9000:9000
    networks:
      - pluma-network
    
networks:
  pluma-network:
