# To start all app containers and have them talking to each other, in the
# root folder /, run 'docker-compose up'.
# Refer to /README.md for more information.

# Docker Compose File Format Version.
version: "3.7"

services:
  server:
    build:
      context: ./server
    restart: always
    # Ne pas mettre de ports ici normalement
    ports: 
      - 5000:5000
    env_file: ./server/.env

  client:
    build:
      context: ./client
    # This will force server service to build and start before client.
    depends_on:
      - server
    restart: always
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
