#  Dockerfile for Node Express Backend
FROM node:15.1-alpine

# Ajout de dumb init pour le PID 1
RUN apk add dumb-init

# Create App Directory
COPY . /app

# Working directory be app
WORKDIR /app

# Installing dependencies.
RUN npm install cors
RUN npm install mariadb
RUN npm i -g nodemon
RUN npm i

# Install MariaDB client
RUN apk --no-cache add mariadb-client

EXPOSE 3001

# Passage en user node
USER node

CMD ["dumb-init","npm","start"]
